name: Update Rules
on: 
  schedule:
    - cron: '0 22,10 * * *'
  push:
   branches:
    - main

  workflow_dispatch:
    
env:
  SCKEY: ${{ secrets.SCKEY }}
  TG_TOKEN: ${{ secrets.TG_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}
  
jobs:
  myjob:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@main
      - name: Update rules
        run: |
          cmd
          .\script\adblock\mio.bat
          .\script\adguard\mio.bat
          .\script\dns\mio.bat
          .\script\allow\mio.bat
          .\script\hosts\mio.bat
          .\script\hosts-youtube\mio.bat
      - name: Git push assets to Github
        run: |
          git init
          git config --local user.name "actions"
          git config --local user.email "action@github.com"
          git gc --prune=now --aggressive
          git branch -m main
          git add --all
          git commit -m "Updated at $(date)"
          git remote add origin "https://github.com/Cats-Team/AdRules.git"
          #git remote set-url --add origin "https://${{ secrets.CODING_ACCOUNT }}:${{ secrets.CODING_PASSWORD }}@e.coding.net/cats-team/adguard/AdRules.git"
          #git fetch --unshallow origin
          git push -u -f origin --all
      
#      - name: Git push assets to Coding
#        run: |
#          git init
#          git config --local user.name "hacamer"
#          git config --local user.email "hcamer145@gmail.com"
#          git branch -m main
#          git add --all
#          git commit -m "Updated at $(date)"
#          git remote rm origin
#          git remote add origin "https://${{ secrets.CODING_ACCOUNT }}:${{ secrets.CODING_PASSWORD }}@e.coding.net/cats-team/adguard/AdRules.git"
#          git config --global credential.git.example.com.provider generic
 #         git fetch --unshallow origin
 #         git push -u -f origin main
 #     - name: Push message to PushPush
 #       run: |
 #         pip3 install requests
 #         pip3 install itertools
 #         pip3 install post
 #         python3 .\pusher.py

