name: Push to Coding
on: push

jobs:
  Pushed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main  
      - name: Git push assets to github & coding
        run: |
          rm -rf .git/
          git init
          git config --local user.name "hacamer"
          git config --local user.email "hcamer145@gmail.com"
          git branch -m main
          git add --all
          git commit -m "Updated at $(date)"
          git remote add origin "https://${{ secrets.CODING_ACCOUNT }}:${{ secrets.CODING_PASSWORD }}@e.coding.net/cats-team/adguard/AdRules.git"
          #git fetch --unshallow origin
          git push -u -f origin main
