name: Push to Coding
on:
 schedule:
    - cron: '0 22,10 * * *'
 push:
   branches:
    - main

jobs:
  Pushed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Update Rules
        run: |
          bash ./script/adblock/main.sh
          bash ./script/adguard/main.sh
          bash ./script/dns/main.sh
          bash ./script/allow/main.sh
          bash ./script/hosts/main.sh
          bash ./script/adblock+adguard/main.sh
      - name: Update other rules
        run: |
          cd rules
          wget -O ADgk.txt https://raw.githubusercontent.com/banbendalao/ADgk/master/ADgk.txt
          wget -O kill-baidu-ad.txt https://raw.githubusercontent.com/banbendalao/ADgk/master/kill-baidu-ad.txt
      - name: Move files
        run: |
          cd script
          mv adblock.txt adguard.txt dns.txt hosts.txt allow.txt adblock+adguard.txt ../
      - name: Git push assets to Coding
        run: |
          rm -rf .git/
          git init
          git config --local user.name "hacamer"
          git config --local user.email "hcamer145@gmail.com"
          git branch -m main
          git add --all
          git commit -m "Updated at $(date)"
          git remote add origin "https://${{ secrets.CODING_ACCOUNT }}:${{ secrets.CODING_PASSWORD }}@e.coding.net/cats-team/adguard/AdRules.git"
          #git fetch --unshallow origin
          git push -u -f origin main
